language: node_js
node_js:
  - '0.12'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-derby' ]; then cd .. && eval "mv $currentfolder generator-derby" && cd generator-derby; fi

